# Elaborazione export Autocad

## Importa csv da analizzare
Inserire csv esportato da Autocad senza modifiche

In [15]:
import pandas as pd
import numpy as np
df=pd.read_csv('DATABASE\DB_14.csv')

## Inserimento dati di commessa
Inserisce anche nuove colonne nel dataframe di riferimento
COMMESSA, STEP, STATO, AREA

In [16]:
comm="2313/22"
step="A"
stato="R00"

In [17]:
df.insert(0,'AREA', "" )
df.insert(0,'STATO', stato )
df.insert(0,'STEP', step )
df.insert(0,'COMMESSA', comm )

## Riorganizzazione e pulizia CSV
Modifica headers colonne, modifica valori 'GRUPPO', ordinamento colonne default.

In [18]:
#Dizionario che contiene coppie key-value per sostituzione nomi sbagliati
#Sostituzione headers con nuovi valori dati da dict
head={'Name':'GRUPPO',
'L.TOT':'L.ANTA',
'Count':'Q.TA'
}
df.rename(columns=head, inplace=True)

#Funzione che sostituisce valori dentro GRUPPO
df['GRUPPO'] = df['GRUPPO'].replace({'PF-CODIFICA-BLOCCO-LINEARE-R01': 'ORIZZONTALI'})
df['GRUPPO'] = df['GRUPPO'].replace({'PF-CODIFICA-BLOCCO VERTICALI-R01': 'VERTICALI'})
#Funzione che sostituisce valori dentro tipo parete
df['TIPO_PARETE'] = df['TIPO_PARETE'].replace({'2G-41': '2G_41'})

#Funzione che nomina "porte" in TipCom HF, HE, HG
for n in range(len(df)):
    if df["TIP.COM"][n]=="HF" or df["TIP.COM"][n]=="HG" or df["TIP.COM"][n]=="HE":
        df.at[n,"GRUPPO"]="PORTE"

#Funzione che sostituisce tutti i valori vuoti con zero
#df=df.fillna("")
#df=df.replace("","@")
df=df.replace(".","")

## Riordine colonne e creazione nuovo Dataframe
Database di produzione da inviare a fornitore

In [19]:
#Funzione che riordina le colonne e scrive nuovo dataframe
prod_df=df.loc[:, ["COMMESSA","STEP","STATO","FLOOR","AREA","OFFICE","GRUPPO","TIPO_PARETE","TIP.COM","N°",
"AN","AN-SL","AN-ANTA","HND","L.ANTA","N00","N01",
"L.TOT.","L1","L2","L3","L4","L5","LV.0","LV.0_MANO","LV.0_NOTE","LV.1","LV.1_MANO","LV.1_NOTE",
"LV.2","LV.2_MANO","LV.2_NOTE","LV.3","LV.3_MANO","LV.3_NOTE","LV.4","LV.4_MANO","LV.4_NOTE",
"LV.5","LV.5_MANO","LV.5_NOTE","LV.6","LV.6_MANO","LV.6_NOTE","Q.TA"]
]
prod_df_fornitore=prod_df

In [20]:
prod_df

,COMMESSA,STEP,STATO,FLOOR,AREA,OFFICE,GRUPPO,TIPO_PARETE,TIP.COM,N°,...,LV.4,LV.4_MANO,LV.4_NOTE,LV.5,LV.5_MANO,LV.5_NOTE,LV.6,LV.6_MANO,LV.6_NOTE,Q.TA
0,2313/22,A,R00,14-CON-02,,EL5,ORIZZONTALI,S2G-41,HB,,...,NaN,NaN,NaN,NaN,NaN,NaN,L,DX,,1
1,2313/22,A,R00,14-CON-02,,EL6,ORIZZONTALI,S2G-41,HB,,...,NaN,NaN,NaN,NaN,NaN,NaN,H,DX,,1
2,2313/22,A,R00,14-CON-02,,EL5,ORIZZONTALI,S2G-41,HB,,...,NaN,NaN,NaN,NaN,NaN,NaN,H,DX,,1
3,2313/22,A,R00,14-CON-01,,EL4,ORIZZONTALI,S2G-41,HB,,...,NaN,NaN,NaN,NaN,NaN,NaN,H,DX,,1
4,2313/22,A,R00,14-CON-02,,EL5,ORIZZONTALI,S2G-41,HB,,...,NaN,NaN,NaN,NaN,NaN,NaN,H,DX,,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,2313/22,A,R00,14-CON-01,,EL7,ORIZZONTALI,S2G-41,HA,,...,NaN,NaN,NaN,NaN,NaN,NaN,G,DX,,1
161,2313/22,A,R00,14-CON-01,,EL7,ORIZZONTALI,S2G-41,HA,,...,NaN,NaN,NaN,NaN,NaN,NaN,H-SPEC,DX,,1
162,2313/22,A,R00,14-HDL-02,,EL18,ORIZZONTALI,S2G-41,HA,,...,T012-SUP,I,,MR-POD,DX,,H-SPEC,DX,,1
163,2313/22,A,R00,14-HDL-02,,EL17,ORIZZONTALI,S2G-41,HA,,...,T012-SUP,I,,MR-POD,DX,,H-SPEC,DX,,1
164,2313/22,A,R00,14-HDL-02,,EL18,ORIZZONTALI,S2G-41,HB,,...,T012,I,,MR-POD,DX,,H-SPEC,DX,,1

## PRODUCTION FILE
Esportazione file excel da inviare a fornitore

In [21]:
#Funzione che scrive su nuovo csv
#prod_df.to_csv("Produzione profili.csv", index=False)
prod_df_fornitore.to_excel("ELABORATI\output_fornitore.xlsx", index=False)